version: "3.9"
services:
  db:
    image: mysql
    restart: always
    volumes:
      - './test_db/:/docket-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: "animelovers"
      MYSQL_DATABASE: "crud_go"
    ports: 
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-panimelovers", "-e", "show schemas"]
      interval: 10s 
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_DSN: "root:animelovers@tcp(db:3306)/crud_go?charset=utf8&parseTime=True&loc=Local"
    depends_on:
      db:
        condition: service_healthy
