# fetch quest
GET localhost:8080/api/student/evaluate?subject_id=1&class=A
Content-Type: application/json
Authorization: Bearer 

##############

# answer quest
POST localhost:8080/api/student/evaluate?subject_id=1&teacher_id=2&class=A
Content-Type: application/json
Authorization: Bearer 

< ./data/quest/answer.json

##############

# answer quest
GET localhost:8080/api/teacher/evaluate?subject_id=1&teacher_id=2&class=A
Content-Type: application/json
Authorization: Bearer 
