# fetch major
GET localhost:8080/api/major
Content-Type: application/json
Authorization: Bearer 

##############

# create major
POST localhost:8080/api/major
Content-Type: application/json
Authorization: Bearer 

< ./data/major/insert.json
##############

# update major
PUT localhost:8080/api/major/1/update
Content-Type: application/json
Authorization: Bearer 

< ./data/major/update.json
##############

# delete major
DELETE localhost:8080/api/major/1/delete
Content-Type: application/json
Authorization: Bearer 

##############
