# fetch questionnaire
GET localhost:8080/questionnaire
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############

# fetch my questionnaire
GET localhost:8080/dashboard
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/quest/fetch_by_tag.json
##############

# fetch questionnaire by id
GET localhost:8080/questionnaire/23
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

# create questionnaire
POST http://localhost:8080/questionnaire
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/quest/insert.json
##############

# update questionnaire
PUT localhost:8080/questionnaire/1/update
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/quest/update.json
##############

# delete questionnaire
DELETE localhost:8080/questionnaire/1/delete
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############
