# fetch quest
GET localhost:8080/api/quest
Content-Type: application/json
Authorization: Bearer 

< ./data/quest/filter_by_user_id.json
##############

# fetch my quest
GET localhost:8080/api/quest/available
Content-Type: application/json
Authorization: Bearer 

< ./data/quest/fetch_by_tag.json

##############

# answer quest
POST localhost:8080/api/quest/answer
Content-Type: application/json
Authorization: Bearer 

< ./data/quest/answer.json

##############

# fetch quest by id
GET localhost:8080/api/quest/1
Content-Type: application/json
Authorization: Bearer 

##############

# fetch response by quest id
GET localhost:8080/api/quest/1/response
Content-Type: application/json
Authorization: Bearer 

##############

# create quest
POST http://localhost:8080/api/quest
Content-Type: application/json
Authorization: Bearer 

< ./data/quest/insert.json

##############

# update quest
PUT localhost:8080/api/quest/1/update
Content-Type: application/json
Authorization: Bearer 

< ./data/quest/update.json

##############

# delete quest
DELETE localhost:8080/api/quest/1/delete
Content-Type: application/json
Authorization: Bearer 

##############
