# fetch subject
GET localhost:8080/subject
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############

# create subject
POST localhost:8080/subject
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/subject/insert.json
##############

# update subject
PUT localhost:8080/subject/1/update
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/subject/update.json
##############

# delete subject
DELETE localhost:8080/subject/1/delete
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############
