# fetch tag
GET localhost:8080/tag
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############

# create tag
POST localhost:8080/tag
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/tag/insert.json
##############

# update tag
PUT localhost:8080/tag/1/update
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/tag/update.json
##############

# delete tag
DELETE localhost:8080/tag/1/delete
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############
