# fetch tag
GET localhost:8080/api/tag
Content-Type: application/json
Authorization: Bearer 

##############

# create tag
POST localhost:8080/api/tag
Content-Type: application/json
Authorization: Bearer 

< ./data/tag/insert.json
##############

# update tag
PUT localhost:8080/api/tag/1/update
Content-Type: application/json
Authorization: Bearer 

< ./data/tag/update.json
##############

# delete tag
DELETE localhost:8080/api/tag/1/delete
Content-Type: application/json
Authorization: Bearer 

##############
