# fetch user
GET localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############

# fetch user by id
GET localhost:8080/api/user/1
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

# create user
POST localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/user/insert.json
##############

# update user
PUT localhost:8080/api/user/3/update
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

< ./data/user/update.json
##############

# delete user
DELETE localhost:8080/api/user/1/delete
Content-Type: application/json
Authorization: Bearer <token_string_from_login>

##############
