// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	request "go-question-board/internal/core/models/request"

	response "go-question-board/internal/core/models/response"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// Login provides a mock function with given fields: _a0
func (_m *AuthRepository) Login(_a0 request.LoginRequest) (response.UserResponse, error) {
	ret := _m.Called(_a0)

	var r0 response.UserResponse
	if rf, ok := ret.Get(0).(func(request.LoginRequest) response.UserResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.UserResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(request.LoginRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields:
func (_m *AuthRepository) RefreshToken() {
	_m.Called()
}
