// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	models "go-question-board/internal/core/models"

	mock "github.com/stretchr/testify/mock"
)

// SubjectRepository is an autogenerated mock type for the SubjectRepository type
type SubjectRepository struct {
	mock.Mock
}

// CreateSubject provides a mock function with given fields: _a0
func (_m *SubjectRepository) CreateSubject(_a0 models.SubjectModel) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.SubjectModel) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSubject provides a mock function with given fields: _a0
func (_m *SubjectRepository) DeleteSubject(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadSubject provides a mock function with given fields:
func (_m *SubjectRepository) ReadSubject() (*[]models.SubjectModel, error) {
	ret := _m.Called()

	var r0 *[]models.SubjectModel
	if rf, ok := ret.Get(0).(func() *[]models.SubjectModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.SubjectModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSubject provides a mock function with given fields: _a0, _a1
func (_m *SubjectRepository) UpdateSubject(_a0 int, _a1 models.SubjectModel) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, models.SubjectModel) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
