// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	models "go-question-board/internal/core/models"

	mock "github.com/stretchr/testify/mock"

	request "go-question-board/internal/core/models/request"

	response "go-question-board/internal/core/models/response"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: _a0
func (_m *UserRepository) CreateUser(_a0 request.UserRequest) (response.UserResponse, error) {
	ret := _m.Called(_a0)

	var r0 response.UserResponse
	if rf, ok := ret.Get(0).(func(request.UserRequest) response.UserResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.UserResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(request.UserRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: _a0
func (_m *UserRepository) DeleteUser(_a0 models.UserModel) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.UserModel) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadUser provides a mock function with given fields:
func (_m *UserRepository) ReadUser() ([]response.UserResponse, error) {
	ret := _m.Called()

	var r0 []response.UserResponse
	if rf, ok := ret.Get(0).(func() []response.UserResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: _a0
func (_m *UserRepository) UpdateUser(_a0 models.UserModel) (response.UserResponse, error) {
	ret := _m.Called(_a0)

	var r0 response.UserResponse
	if rf, ok := ret.Get(0).(func(models.UserModel) response.UserResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.UserResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.UserModel) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
